server:
  port: 7077

cloud:
  aws:
    region:
      static: us-east-2
    stack:
      auto: false

application:
  aws:
    credentials:
      access-key: AKIAWMDOQGSXU4Z4AKEF
      secret-key: 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
    sns: # simple notification service
      arn: # amazon resource name
        otp-topic-arn: arn:aws:sns:us-east-2:438318412975:OTP-Topic

